# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:smartq}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  # Redis 配置
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: 6379
    timeout: 5000
    password: ${REDIS_PASSWORD:password}
  # Elasticsearch 配置
  # todo 需配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: ${ES_PASSWORD:password}
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: ${KNIFE4J_USERNAME:admin}
    password: ${KNIFE4J_PASSWORD:password}
ai:
  apiKey: ${AI_API_KEY:your_api_key_here}

# 对象存储
cos:
  client:
    accessKey: ${COS_ACCESS_KEY:your_access_key_here}
    secretKey: ${COS_SECRET_KEY:your_secret_key_here}
    region: ap-guangzhou
    bucket: smartq-1360790171