# Spring Boot 配置文件
spring:
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: prod
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartq
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
  # todo 需配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0 # 绑定所有IP地址，允许其他设备访问（如前端部署在别的服务器）
  port: 8101 # 项目启动端口，访问地址为 http://localhost:8101
  servlet:
    context-path: /api # 项目路径前缀，例如实际接口为 http://localhost:8101/api/user/login
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
cos:
  client:
    accessKey: ${COS_ACCESS_KEY:your_access_key_here}
    secretKey: ${COS_SECRET_KEY:your_secret_key_here}
    region: ap-guangzhou
    bucket: smartq-1360790171
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cf.smartq.controller
ai:
  apiKey: 6e048e41f2474d40b598564d54b4c3ac.0aP26tnlyDKAtQOe
  request-timeout: 120
  connect-timeout: 10
  read-timeout: 10
  write-timeout: 10
